export enum PermissionEnum {
    LOGIN = 'LOGIN',
    GENERATE_PROFILE = 'GENERATE_PROFILE',
    CHANGE_TEMPORAL_PASSWORD = 'CHANGE_TEMPORAL_PASSWORD',
    CREATE_PROFILE = 'CREATE_PROFILE',
    UPDATE_PROFILE = 'UPDATE_PROFILE',
    DELETE_PROFILE = 'DELETE_PROFILE',
    VIEW_PROFILE = 'VIEW_PROFILE',
    VIEW_ALL_PROFILE = 'VIEW_ALL_PROFILE',
    VIEW_ALL_MESSAGES = 'VIEW_ALL_MESSAGES'
}